version: "3.9"
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "mrmixr_dev_db"
      POSTGRES_USER: "mrmixr_dev_user"
      POSTGRES_PASSWORD: "local_dev_pwd"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: