// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Konstantinov-Innokentii/mrmixr/api/models"
)

// CreateCheckCreatedCode is the HTTP code returned for type CreateCheckCreated
const CreateCheckCreatedCode int = 201

/*CreateCheckCreated PR check created

swagger:response createCheckCreated
*/
type CreateCheckCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Check `json:"body,omitempty"`
}

// NewCreateCheckCreated creates CreateCheckCreated with default headers values
func NewCreateCheckCreated() *CreateCheckCreated {

	return &CreateCheckCreated{}
}

// WithPayload adds the payload to the create check created response
func (o *CreateCheckCreated) WithPayload(payload *models.Check) *CreateCheckCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create check created response
func (o *CreateCheckCreated) SetPayload(payload *models.Check) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCheckCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateCheckDefault General errors

swagger:response createCheckDefault
*/
type CreateCheckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCheckDefault creates CreateCheckDefault with default headers values
func NewCreateCheckDefault(code int) *CreateCheckDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateCheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create check default response
func (o *CreateCheckDefault) WithStatusCode(code int) *CreateCheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create check default response
func (o *CreateCheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create check default response
func (o *CreateCheckDefault) WithPayload(payload *models.Error) *CreateCheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create check default response
func (o *CreateCheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
