// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateCheckHandlerFunc turns a function with the right signature into a create check handler
type CreateCheckHandlerFunc func(CreateCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCheckHandlerFunc) Handle(params CreateCheckParams) middleware.Responder {
	return fn(params)
}

// CreateCheckHandler interface for that can handle valid create check params
type CreateCheckHandler interface {
	Handle(CreateCheckParams) middleware.Responder
}

// NewCreateCheck creates a new http.Handler for the create check operation
func NewCreateCheck(ctx *middleware.Context, handler CreateCheckHandler) *CreateCheck {
	return &CreateCheck{Context: ctx, Handler: handler}
}

/* CreateCheck swagger:route POST /checks createCheck

CreateCheck create check API

*/
type CreateCheck struct {
	Context *middleware.Context
	Handler CreateCheckHandler
}

func (o *CreateCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCheckParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateCheckBody create check body
//
// swagger:model CreateCheckBody
type CreateCheckBody struct {

	// days
	Days []int64 `json:"days"`

	// github repositories
	GithubRepositories []int64 `json:"github_repositories"`

	// hour
	Hour int64 `json:"hour,omitempty"`

	// minute
	Minute int64 `json:"minute,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// tz
	Tz string `json:"tz,omitempty"`
}

// Validate validates this create check body
func (o *CreateCheckBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create check body based on context it is used
func (o *CreateCheckBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateCheckBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCheckBody) UnmarshalBinary(b []byte) error {
	var res CreateCheckBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
