// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCheckHandlerFunc turns a function with the right signature into a delete check handler
type DeleteCheckHandlerFunc func(DeleteCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCheckHandlerFunc) Handle(params DeleteCheckParams) middleware.Responder {
	return fn(params)
}

// DeleteCheckHandler interface for that can handle valid delete check params
type DeleteCheckHandler interface {
	Handle(DeleteCheckParams) middleware.Responder
}

// NewDeleteCheck creates a new http.Handler for the delete check operation
func NewDeleteCheck(ctx *middleware.Context, handler DeleteCheckHandler) *DeleteCheck {
	return &DeleteCheck{Context: ctx, Handler: handler}
}

/* DeleteCheck swagger:route DELETE /checks/{id} deleteCheck

DeleteCheck delete check API

*/
type DeleteCheck struct {
	Context *middleware.Context
	Handler DeleteCheckHandler
}

func (o *DeleteCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCheckParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
