// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Konstantinov-Innokentii/mrmixr/api/models"
)

// DeleteCheckNoContentCode is the HTTP code returned for type DeleteCheckNoContent
const DeleteCheckNoContentCode int = 204

/*DeleteCheckNoContent Deleted

swagger:response deleteCheckNoContent
*/
type DeleteCheckNoContent struct {
}

// NewDeleteCheckNoContent creates DeleteCheckNoContent with default headers values
func NewDeleteCheckNoContent() *DeleteCheckNoContent {

	return &DeleteCheckNoContent{}
}

// WriteResponse to the client
func (o *DeleteCheckNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteCheckDefault General errors

swagger:response deleteCheckDefault
*/
type DeleteCheckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCheckDefault creates DeleteCheckDefault with default headers values
func NewDeleteCheckDefault(code int) *DeleteCheckDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete check default response
func (o *DeleteCheckDefault) WithStatusCode(code int) *DeleteCheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete check default response
func (o *DeleteCheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete check default response
func (o *DeleteCheckDefault) WithPayload(payload *models.Error) *DeleteCheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete check default response
func (o *DeleteCheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
