// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListGithubRepositoriesHandlerFunc turns a function with the right signature into a list github repositories handler
type ListGithubRepositoriesHandlerFunc func(ListGithubRepositoriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListGithubRepositoriesHandlerFunc) Handle(params ListGithubRepositoriesParams) middleware.Responder {
	return fn(params)
}

// ListGithubRepositoriesHandler interface for that can handle valid list github repositories params
type ListGithubRepositoriesHandler interface {
	Handle(ListGithubRepositoriesParams) middleware.Responder
}

// NewListGithubRepositories creates a new http.Handler for the list github repositories operation
func NewListGithubRepositories(ctx *middleware.Context, handler ListGithubRepositoriesHandler) *ListGithubRepositories {
	return &ListGithubRepositories{Context: ctx, Handler: handler}
}

/* ListGithubRepositories swagger:route GET /github_repositories listGithubRepositories

ListGithubRepositories list github repositories API

*/
type ListGithubRepositories struct {
	Context *middleware.Context
	Handler ListGithubRepositoriesHandler
}

func (o *ListGithubRepositories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListGithubRepositoriesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
