// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Konstantinov-Innokentii/mrmixr/api/models"
)

// ListGithubRepositoriesOKCode is the HTTP code returned for type ListGithubRepositoriesOK
const ListGithubRepositoriesOKCode int = 200

/*ListGithubRepositoriesOK OK

swagger:response listGithubRepositoriesOK
*/
type ListGithubRepositoriesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.GithubRepository `json:"body,omitempty"`
}

// NewListGithubRepositoriesOK creates ListGithubRepositoriesOK with default headers values
func NewListGithubRepositoriesOK() *ListGithubRepositoriesOK {

	return &ListGithubRepositoriesOK{}
}

// WithPayload adds the payload to the list github repositories o k response
func (o *ListGithubRepositoriesOK) WithPayload(payload []*models.GithubRepository) *ListGithubRepositoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list github repositories o k response
func (o *ListGithubRepositoriesOK) SetPayload(payload []*models.GithubRepository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGithubRepositoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.GithubRepository, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListGithubRepositoriesDefault General errors

swagger:response listGithubRepositoriesDefault
*/
type ListGithubRepositoriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListGithubRepositoriesDefault creates ListGithubRepositoriesDefault with default headers values
func NewListGithubRepositoriesDefault(code int) *ListGithubRepositoriesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListGithubRepositoriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list github repositories default response
func (o *ListGithubRepositoriesDefault) WithStatusCode(code int) *ListGithubRepositoriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list github repositories default response
func (o *ListGithubRepositoriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list github repositories default response
func (o *ListGithubRepositoriesDefault) WithPayload(payload *models.Error) *ListGithubRepositoriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list github repositories default response
func (o *ListGithubRepositoriesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGithubRepositoriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
