// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Konstantinov-Innokentii/mrmixr/api/models"
)

// ListChecksOKCode is the HTTP code returned for type ListChecksOK
const ListChecksOKCode int = 200

/*ListChecksOK OK

swagger:response listChecksOK
*/
type ListChecksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Check `json:"body,omitempty"`
}

// NewListChecksOK creates ListChecksOK with default headers values
func NewListChecksOK() *ListChecksOK {

	return &ListChecksOK{}
}

// WithPayload adds the payload to the list checks o k response
func (o *ListChecksOK) WithPayload(payload []*models.Check) *ListChecksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list checks o k response
func (o *ListChecksOK) SetPayload(payload []*models.Check) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListChecksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Check, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListChecksDefault General errors

swagger:response listChecksDefault
*/
type ListChecksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListChecksDefault creates ListChecksDefault with default headers values
func NewListChecksDefault(code int) *ListChecksDefault {
	if code <= 0 {
		code = 500
	}

	return &ListChecksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list checks default response
func (o *ListChecksDefault) WithStatusCode(code int) *ListChecksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list checks default response
func (o *ListChecksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list checks default response
func (o *ListChecksDefault) WithPayload(payload *models.Error) *ListChecksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list checks default response
func (o *ListChecksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListChecksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
