// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveCheckHandlerFunc turns a function with the right signature into a retrieve check handler
type RetrieveCheckHandlerFunc func(RetrieveCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveCheckHandlerFunc) Handle(params RetrieveCheckParams) middleware.Responder {
	return fn(params)
}

// RetrieveCheckHandler interface for that can handle valid retrieve check params
type RetrieveCheckHandler interface {
	Handle(RetrieveCheckParams) middleware.Responder
}

// NewRetrieveCheck creates a new http.Handler for the retrieve check operation
func NewRetrieveCheck(ctx *middleware.Context, handler RetrieveCheckHandler) *RetrieveCheck {
	return &RetrieveCheck{Context: ctx, Handler: handler}
}

/* RetrieveCheck swagger:route GET /checks/{id} retrieveCheck

RetrieveCheck retrieve check API

*/
type RetrieveCheck struct {
	Context *middleware.Context
	Handler RetrieveCheckHandler
}

func (o *RetrieveCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRetrieveCheckParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
