// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Check check
//
// swagger:model Check
type Check struct {

	// days
	Days []int64 `json:"days"`

	// github repositories
	GithubRepositories []*GithubRepository `json:"github_repositories"`

	// hour
	Hour int64 `json:"hour,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// minute
	Minute int64 `json:"minute,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// tz
	Tz string `json:"tz,omitempty"`
}

// Validate validates this check
func (m *Check) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGithubRepositories(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Check) validateGithubRepositories(formats strfmt.Registry) error {
	if swag.IsZero(m.GithubRepositories) { // not required
		return nil
	}

	for i := 0; i < len(m.GithubRepositories); i++ {
		if swag.IsZero(m.GithubRepositories[i]) { // not required
			continue
		}

		if m.GithubRepositories[i] != nil {
			if err := m.GithubRepositories[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("github_repositories" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("github_repositories" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this check based on the context it is used
func (m *Check) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGithubRepositories(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Check) contextValidateGithubRepositories(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.GithubRepositories); i++ {

		if m.GithubRepositories[i] != nil {
			if err := m.GithubRepositories[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("github_repositories" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("github_repositories" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Check) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Check) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Check) UnmarshalBinary(b []byte) error {
	var res Check
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
