swagger: "2.0"

info:
  title: MRmixr
  version: 1.0.0
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /checks:
    get:
      operationId: listChecks
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Check"
        default:
          $ref: "#/responses/GenericError"
    post:
      operationId: createCheck
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              github_repositories:
                type: array
                items:
                  type: integer
              hour:
                type: integer
              minute:
                type: integer
              tz:
                type: string
              days:
                type: array
                items:
                  type: integer
      responses:
        201:
          description: PR check created
          schema:
            $ref: '#/definitions/Check'
        default:
          $ref: "#/responses/GenericError"
  /checks/{id}:
    get:
      operationId: retrieveCheck
      parameters:
        - type: integer
          name: id
          in: path
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Check'
        default:
          $ref: "#/responses/GenericError"
    delete:
      operationId: deleteCheck
      parameters:
        - type: integer
          name: id
          in: path
          required: true
      responses:
        204:
          description: Deleted
        default:
          $ref: "#/responses/GenericError"
    put:
      operationId: updateCheck
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              github_repositories:
                type: array
                items:
                  type: integer
              hour:
                type: integer
              minute:
                type: integer
              tz:
                type: string
              days:
                type: array
                items:
                  type: integer
      responses:
        200:
          description: OK
        default:
          $ref: "#/responses/GenericError"
  /github_repositories:
    get:
      operationId: listGithubRepositories
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/GithubRepository"
        default:
          $ref: "#/responses/GenericError"



responses:
  GenericError:
    description: General errors
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    required:
      - message
    properties:
      code:
        description: HTTP code
        type: integer
      message:
        type: string

  Check:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
      hour:
        type: integer
      minute:
        type: integer
      tz:
        type: string
      days:
        type: array
        items:
          type: integer
      github_repositories:
        type: array
        items:
          $ref: '#/definitions/GithubRepository'

  GithubRepository:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        readOnly: true
